repos:
  - repo: https://github.com/TekWizely/pre-commit-golang
    rev: v1.0.0-rc.1
    hooks:
      - id: golangci-lint-mod
      - id: go-mod-tidy
      - id: go-test-mod

  - repo: https://github.com/rubocop-hq/rubocop
    rev: v1.70.0
    hooks:
      - id: rubocop
